### ISSUE TITLE
kontuar

### ISSUE THREAD

**Issue by boolbag** [ogun/guncel-turkce-sozluk#3]
First off, thank you for downloading the whole site. Fewer people will have to scrape it, better for the website. :)
Just wanted to alert you that the word `kontuar`, which had no `anlamlarListe` before, now has one.

[https://sozluk.gov.tr/gts?ara=kontuar](https://sozluk.gov.tr/gts?ara=kontuar)
[https://sozluk.gov.tr/gts_id?id=74553](https://sozluk.gov.tr/gts_id?id=74553)

**Comment by ogun** [comment]
Hello @boolbag, sorry I didn't see your comment before. The new version has been added to the repository.
