### ISSUE TITLE
Can't access the https://www.sozluk.gov.tr/gts_id

### ISSUE THREAD

**Issue by emirhanpisgin** [ogun/guncel-turkce-sozluk#4]
I've been trying to access this endpoint for a while right now and it seems to be doesn't exists anymore.
```
https://www.sozluk.gov.tr/gts_id?id=100
```
I've tried the endpoint with this header
```
"APIs-Google (+https://developers.google.com/webmasters/APIs-Google.html)"
```
but it seems not working is it on me? or the endpoint doesn't exists anymore?

**Comment by ogun** [comment]
Hello @kryparnold, I'm not the website owner, but the API endpoint seems deprecated.
